Added dynamic rendering of Footer component based on user's price sel…
Mol4aliva/elektrikell pull request #2
Opened 2024-01-25 16:52 UTC by Mol4aliva

…ection.

2024-01-25 16:58 UTC, rmehtije requested changes

2024-01-25 16:58 UTC, rmehtije commented on src/Footer/Footer.jsx
> +                {activePrice === 'low' && <TargetLow />}
Используй const вместо low. У нас есть такая DEFAULT_ACTIVE_BUTTON

2024-01-25 17:05 UTC, Mol4aliva commented on src/Footer/Footer.jsx
> +                {activePrice === 'low' && <TargetLow />}
Исправила

2024-01-26 10:37 UTC, rasim-mehtijev approved these changes

2024-01-26 10:38 UTC, merged